---
- name: 'install docker dependencies'
  yum:
    name: '{{ dependencies }}'
    state: 'latest'

- name: 'add docker repo'
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0

- name: Install Docker
  package:
    name: '{{ docker }}'
    state: latest
  notify:
    - Up Docker

- name: Create a network with custom IPAM config
  docker_network:
    name: net_cd
    ipam_config:
      - subnet: 172.10.27.0/24
        gateway: 172.10.27.1
        aux_addresses:
          nginx: 172.10.27.2
          flask1: 172.10.27.3
          flask2: 172.10.27.4
          flask3: 172.10.27.5